language: dart

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache

dart:
  - dev

jobs:
  include:
    - stage: analyze_and_format
      name: "Analyze"
      os: linux
      script: dartanalyzer --enable-experiment=non-nullable --fatal-warnings --lints .
    - stage: analyze_and_format
      name: "Format"
      os: linux
      script: dartfmt -n --set-exit-if-changed .
    - stage: test
      name: "Test"
      os: linux
      script: pub run --enable-experiment=non-nullable test
